### ISSUE TITLE
Option for limiting number of colums printed

### ISSUE THREAD

**Issue by matthew-phelps** [MilesMcBain/paint#13]
It would be nice to have an option to limit the number of columns that are printed, with perhaps a message naming variables omitted (like the default tibble print, or the `truc.cols = TRUE` option for `print.data.table`). I often work with very wide data.tables and don't want to have to scroll up a lot every time I print out.

I love this package by the way, so thank you for making it!

**Comment by MilesMcBain** [comment]
One of the main inspirations for this package was my frustration with the truncation behaviour of tibbles. So I can't see myself getting motivated to implement something like that.

I too often work with data that exceed my console height when painted, one thing that helps is to bind keyboard shortcuts to scroll the terminal up and down, so you can view the output you want without switching to another pane, or taking your hands off the keyboard.

This is easy to do in VSCode, but not possible in RStudio AFIK.

**Comment by matthew-phelps** [comment]
Fair enough, and thanks for the reply.
